name: deploy-to-aws

on:
  push:
    branches: [ main ]

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependancies
        run: npm install
      - name: Run Tests
        run: npm run test
      - name: Push Docker Image to ECR
        run: echo "pushing docker image ..."
  deploy-to-aws:
    needs: [test-and-build]
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to AWS
        run: echo 'updating ecs service ...'
    
